version: '3.8'

services:
  watchdog:
    container_name: nimiq-watchdog
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 12345:12345
    environment:
      - NIMIQ_HOST=https://rpc-testnet.nimiqcloud.com
      - NIMIQ_PORT=443
      - RETRY_LIMIT=10
      - RETRY_DELAY=10
      - RESTART_DELAY=300
      - DOCKER_CONTAINER_NAME=node
      - PROMETHEUS_PORT=12345
    restart: unless-stopped
